version: '3'

services:
  web:
    container_name: project_management
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - net

  db:
    image: postgres:12.2
    restart: always
    environment:
      - POSTGRES_DB=project_management
      - POSTGRES_USER=Rigel
      - POSTGRES_PASSWORD=Betelgeuse
    networks:
      net:
        aliases:
        - net_alias

networks:
  net: