# Generated by Django 3.0.4 on 2020-05-05 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprints', '0002_auto_20200504_1632'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_person',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Medium Low'), (0, 'Low')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('Backlog', 'Backlog'), ('To Do', 'Todo'), ('In Progress', 'In Progress'), ('QA', 'Quality Assurance'), ('Done', 'Done')], default='Backlog', max_length=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sprints.Sprint'),
        ),
        migrations.AlterField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(blank=True),
        ),
    ]
