# Generated by Django 3.0.4 on 2020-05-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200505_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
