# Generated by Django 3.0.4 on 2020-05-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_auto_20200504_1632'),
        ('tasks', '0004_auto_20200505_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sprints.Sprint'),
        ),
    ]
