# Generated by Django 3.0.4 on 2020-04-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectparticipants',
            name='status',
            field=models.CharField(default='Waiting', max_length=10),
        ),
    ]
